// Theme
export const TOGGLE_LIGHT_THEME = "TOGGLE_LIGHT_THEME";
export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";

// LogIn
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const EXPIRE_LOGIN_SESSION = "EXPIRE_LOGIN_SESSION";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SAVE_USER_DATA = "SAVE_USER_DATA";

export const KEEP_USER_SIGNIN = "KEEP_USER_SIGNIN";

export const FORGET_PASSWORD_KEY = "FORGET_PASSWORD_KEY";

export const UPDATE_FCM_TOKEN = "UPDATE_FCM_TOKEN";

export const IS_UPDATE_AVAILABLE = "IS_UPDATE_AVAILABLE";

export const SET_USERS_VEHICLE = "SET_USERS_VEHICLE";


// Home
export const SET_HOME_DETAILS = "SET_HOME_DETAILS";
export const UPDATE_USER_WALLET_BALANCE = "UPDATE_USER_WALLET_BALANCE";
export const SET_USER_CURRENT_LOCATION = "SET_USER_CURRENT_LOCATION";

// notification
export const SET_NOTIFICATION_DATA = "SET_NOTIFICATION_DATA";

// charging
export const RESET_CHARGING_REDUX = "RESET_CHARGING_REDUX";
export const SET_USER_SELECTED_CONNECTOR = "SET_USER_SELECTED_CONNECTOR";
export const SET_VERIFY_CHARGING_DATA = "SET_VERIFY_CHARGING_DATA";
export const SET_CHARGING_ON_START = "SET_CHARGING_ON_START";
export const MARK_AS_CHARGING_COMPLETE = "MARK_AS_CHARGING_COMPLETE";

